### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by meiyank** [rabanti-github/NanoXLSX4j#1] opened 2020-09-25 08:41 UTC
Fatal Exception: io.reactivex.exceptions.UndeliverableException
The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | No direct method <init>(Ljava/io/OutputStream;Ljava/nio/charset/Charset;)V in class Ljava/util/zip/ZipOutputStream; or its super classes (declaration of 'java.util.zip.ZipOutputStream' appears in /system/framework/core-libart.jar)
io.reactivex.plugins.RxJavaPlugins.onError

Caused by java.lang.NoSuchMethodError
No direct method <init>(Ljava/io/OutputStream;Ljava/nio/charset/Charset;)V in class Ljava/util/zip/ZipOutputStream; or its super classes (declaration of 'java.util.zip.ZipOutputStream' appears in /system/framework/core-libart.jar)

ch.rabanti.nanoxlsx4j.lowLevel.Packer.pack (Packer.java:160)
ch.rabanti.nanoxlsx4j.lowLevel.XlsXWriter.saveAsStream (XlsXWriter.java:1170)
ch.rabanti.nanoxlsx4j.Workbook.saveAsStream (Workbook.java:569)

**Comment by rabanti-github** [comment] 2020-09-25 09:04
Hello,
It looks, like you are using RxJava. Can you provide some lines of code to this issue?
How do you try to call the saveAsStream() method? Do you want to reuse the stream?

Thank you in advance.

**Comment by meiyank** [comment] 2020-09-25 09:54
mCheckPermissionUseCase
                .execute(Permission.WriteExternalStorage)
                .doOnTerminate(() -> {
                    if (view != null) {
                        view.progressBarLoading(false);
                    }
                })
                .compose(bindToLifecycle())
                .subscribe(result -> {
                    if (null != view) {
                        if (result) {
                            view.storagePermissionGranted();
                            try (FileOutputStream out = context.openFileOutput(fileName, Context.MODE_PRIVATE)) {
                                data.saveAsStream(out);
                                File file = new File(context.getFilesDir(), fileName);
                                view.openShareFileIntent(file, fileFormat);
                            } catch (Exception ex) {
                                NBLogger.d(TAG, ex.getMessage());
                                view.onError(ex.getMessage());
                            }
                        } else {
                            view.storagePermissionDenied();
                        }
                    }
                });

**Comment by rabanti-github** [comment] 2020-09-25 22:21
Hello.
It looks, like you are using AndroidStudio, right?
In this case, I cannot really help you, unfortunately. PicoXLSX4j and NanoXLSX4j were developed for 'standard' JDK/JRE environments (e.g. java applications running with OpenJDK >=8). So, it's possible that parts of the library - namely ZipOutputStream - are differently implemented in Android. I cannot really say...

What I could recommend is to create a fork of nanoXLSX4j and try to track down the incompatible part(s) of the ADK.
For an easier debugging, The reactive components (e.g. RxJava) can be left out (or using just blockingGet for test purposes)
You will probably find the cause of this error in the class: [https://github.com/rabanti-github/NanoXLSX4j/blob/master/src/main/java/ch/rabanti/nanoxlsx4j/lowLevel/Packer.java](https://github.com/rabanti-github/NanoXLSX4j/blob/master/src/main/java/ch/rabanti/nanoxlsx4j/lowLevel/Packer.java).
I could imagine that File- and Stream-Handling in Android has some restrictions in comparison to Vanilla Java.

**Comment by rabanti-github** [comment] 2020-10-08 23:10
I will close this issue for now.
Please let me know, if you need more information about the library, or advice how to port it to ADK.

**Closed as completed by rabanti-github** 2020-10-08 23:10 UTC
